### ISSUE TITLE
I remain unverified(:

### ISSUE THREAD

**Issue by rbelew** [mckinnon/simple-mastodon-verification#1]
hi, thanks for this plugin, just what i was looking for!

but I am still having a problem, connecting https://opalstack.social/@rik
to  http://rikiwiki.electronicartifacts.com.  any guesses why?

i'm also confused by the "Author verification" verification bit:
it mentions an "Author's archive page" but (I am such a WP newby that)
I don't even know if my old (Twenty Eleven) theme even supports archives?

**Comment by rbelew** [comment]
update:  the issue turned out to be needing a certificate supporting HTTPS (vs http).

**Comment by mckinnon** [comment]
This is helpful for others. Thank you. It's a Mastodon cache thing.

This plugin (and Mastodon) should accept both http and https.

You have to refresh the URL on your Mastodon profile before Mastodon will check for verification. Changing https to http should work as well as the reverse, but so too will removing the http URL entirely and then re-adding it.

Related: if you verify and then turn off the Plugin, it will look _to you_ like verification persists but others checking for the first time won't see the verification bar. (simplified, exceptions exist, YMMV, etc)

**Comment by rbelew** [comment]
I had already discovered that the verification check happens on profile save, but that didn't make it work.  and a few other hacks, too.  but as soon as  i provided https certificate support on my wordpress server, it worked.  FYI.

**Comment by mckinnon** [comment]
Just checked the [Mastodon 4.0.0 change log](https://github.com/mastodon/mastodon/blob/03b0f3ac83edfc46d304bfca1539ca6000e36fc3/CHANGELOG.md). You're right.
_"Change link verification to only work for https links"._

I'll update the plugin.
