### ISSUE TITLE
Add support for new fediverse:creator meta tag 

### ISSUE THREAD

**Issue by lexpostma** [mckinnon/simple-mastodon-verification#5]
In July [Mastodon announced](https://blog.joinmastodon.org/2024/07/highlighting-journalism-on-mastodon/) they are going to introduce a new creator meta tag:

```<meta name="fediverse:creator" content="@Gargron@mastodon.social" />.```

This is now available with [Mastodon version 4.3](https://blog.joinmastodon.org/2024/10/mastodon-4.3/#helping-writers-and-journalists). Would be really nice if this plugin could support this too, by using the Mastodon ID from the author’s profile.

**Comment by mckinnon** [comment]
Thanks for the suggestion @lexpostma. It's a good one but I don't feel matches the philosophy of this plugin: simple and without feature-creep.

Supporting the fediverse:creator meta tag requires implementing Open Graph meta tags, and then I'm shaving the yak.

[ActivityPub ](https://wordpress.org/plugins/activitypub/)+ [Open Graph](https://wordpress.org/plugins/opengraph/) do that job well.

**Comment by lexpostma** [comment]
Ah, those were 5 glorious hours of use, haha. It’s a bummer but understandable, you want to keep the plugin focussed and single purpose.

The ActivityPub plugin doesn’t support customisable Mastodon profiles, it assumes you want to use your WordPress install as your ActivityPub profile. In my case I don’t want that (yet) for my personal profile, I want to keep using Mastodon.social.

The Open Graph plugin does indeed support exactly what I need. However it now duplicates my `og:` tags, because The SEO Framework plugin also add those in a more customisable way. So I’ve made a similar request for `fediverse:creator` support to them [in an issue](https://github.com/sybrew/the-seo-framework/issues/690).

Thanks for moving quickly and for the suggestions. I appreciate your opinionated stance for the plugin.

**Comment by mckinnon** [comment]
Was v.2.0.0 actually useful to you? I didn't get it to work as intended. If it has a use, I can add that part back. The ActivityPub plugin supports customizable Mastodon profiles but I found the settings unintuitive. 

To enable per-user `fediverse:creator` on posts: Settings>ActivityPub>Settings. Enable Author-Profiles. Edit your user and add your handle to the "Fediverse (username@host.tld)" (I toggled ActivityPub>Settings>General:OpenGraph a couple times but I don't know if that mattered.)

Enabling site-wide `fediverse:creator` (i.e. on homepage) doesn't allow changing the domain name.

If you do want to use Open Graph but want to remove some duplicates, you can disable them using filters and returning null.

**Comment by lexpostma** [comment]
2.0.0 did exactly what I wanted: add a site wide `fediverse:creator` tag for the Mastodon profile I defined in  Settings>General, and an article specific tag from the author’s profile.

The ActivityPub plugin does not allow for changing your Fediverse profile to anything custom. It’s fixed to `@[wp username]@[wp domain]`. You can enable the ActivityPub capability per user/author though, but that’s on or off, nothing else.

The setting you’re referring to — Users>Profile>Contact Info>Fediverse (username@host.tld) — is coming from the Open Graph plugin, not the ActivityPub one. So without Open Graph that setting is gone.

My goal: 
* Have my WP blog itself be on the Fediverse with its site wide profile, so people can follow it there. Can be achieved through the ActivityPub plugin
* Have authors be recognised and connected on their personal Mastodon profile (any instance/domain) with sharing a link on Mastodon. Myself site wide (general settings) or specific authors per article. 
   * Can’t be done with ActivityPub plugin, profiles will be fixed to WP domain
   * Could be achieved though Open Graph plugin, but that duplicates my meta tags due to another SEO plugin
   * Was shortly achieved with your v2 of SMV plugin, which added `fediverse:creator` from site settings and author’s profiles
   * Might be achieved with The SEO Framework plugin, [if this goes well](https://github.com/sybrew/the-seo-framework/issues/690)

If you’d add it back, and my SEO plugin does so too, I would use the SEO’s feature over SMV’s just to keep things centralised. It’s up to you if you want to add it back. Again, I completely understand if you prefer to keep it focused, and I have high hopes for the other plugin.

**Comment by mckinnon** [comment]
A use-case I didn't consider. I'll get something up soon.

**Comment by mckinnon** [comment]
Try [Simple fediverse:creator](https://github.com/mckinnon/simple-fediverse-creator). It should be up on the Plugin store this week.

It should do what you want (more correctly) until the tag is adopted more widely.

**Comment by lexpostma** [comment]
That’s amazing, you created a whole new plugin. Thank you! I’ll install it once it’s on the store.
